baseURL = "/"
languageCode = "en-us"
title = "DEBO"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
BackgroundImages = [
# "bg/background.jpg"
# "bg/background2.jpg", 
"bg/background3.jpg"
 ]
BackgroundStyle = "radial-gradient(circle, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 50%, rgba(252,176,69,1) 100%);"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "entertainment"
tag = "entertainment"
icon = "film"

[[ params.nav ]]
name = "development"
tag = "development"
icon = "pencil"

[[ params.nav ]]
name = "social"
tag = "social"
icon = "comment"

[[ params.nav ]]
name = "learn"
tag = "learn"
icon = "book"

[[ params.nav ]]
name = "blockchain"
tag = "blockchain"
icon = "key"

[[ params.nav ]]
name = "downloads"
tag = "downloads"
icon = "download"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-basket"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "cloud"
tag = "cloud"
icon = "cloud"
