baseURL = "/"
languageCode = "en-us"
title = "DEBINUM"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
#BackgroundImages = [
# "bg/background.jpg",
# "bg/background2.jpg", 
# "bg/background3.jpg"
# ]
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-basket"

[[ params.nav ]]
name = "audio"
tag = "audio"
icon = "headphones"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "film"

[[ params.nav ]]
name = "development"
tag = "development"
icon = "edit"

[[ params.nav ]]
name = "social"
tag = "social"
icon = "retweet"

[[ params.nav ]]
name = "wiki"
tag = "wiki"
icon = "user"

[[ params.nav ]]
name = "blockchain"
tag = "blockchain"
icon = "cog"

[[ params.nav ]]
name = "messaging"
tag = "messaging"
icon = "signal"

[[ params.nav ]]
name = "downloads"
tag = "downloads"
icon = "download"


