baseURL = "/"
languageCode = "en-us"
title = "DEBO"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
BackgroundImages = [
"bg/background2.jpg"
# "bg/background2.jpg", 
# "bg/background3.jpg"
 ]
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "film"

[[ params.nav ]]
name = "development"
tag = "development"
icon = "edit"

[[ params.nav ]]
name = "social"
tag = "social"
icon = "retweet"

[[ params.nav ]]
name = "learn"
tag = "learn"
icon = "user"

[[ params.nav ]]
name = "blockchain"
tag = "blockchain"
icon = "qrcode"

[[ params.nav ]]
name = "messaging"
tag = "messaging"
icon = "envelope"

[[ params.nav ]]
name = "downloads"
tag = "downloads"
icon = "download"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "globe"

[[ params.nav ]]
name = "music"
tag = "music"
icon = "music"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "weather"
tag = "weather"
icon = "cloud"

[[ params.nav ]]
name = "cloud"
tag = "cloud"
icon = "save"

[[ params.nav ]]
name = "gaming"
tag = "gaming"
icon = "gamepad"





