baseURL = "/"
languageCode = "en-us"
title = "DEBINUM"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
BackgroundImages = [
"bg/background.jpg"
# "bg/background2.jpg", 
# "bg/background3.jpg"
 ]
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "film"

[[ params.nav ]]
name = "development"
tag = "development"
icon = "edit"

[[ params.nav ]]
name = "social"
tag = "social"
icon = "retweet"

[[ params.nav ]]
name = "wiki"
tag = "wiki"
icon = "user"

[[ params.nav ]]
name = "blockchain"
tag = "blockchain"
icon = "qrcode"

[[ params.nav ]]
name = "messaging"
tag = "messaging"
icon = "envelope"

[[ params.nav ]]
name = "downloads"
tag = "downloads"
icon = "download"


